---
# Yum/APT  Variables
zabbix_repo_version: "7.0"
zabbix_repo_yum_gpgcheck: 0
zabbix_repo_yum_schema: https
zabbix_repo_deb_url: "http://repo.zabbix.com/zabbix/{{ zabbix_repo_version }}/{% if zabbix_repo_version == 7.2 %}stable/{% endif %}{{ ansible_facts.lsb.id | default(ansible_facts['distribution']) | lower }}{% if ansible_facts['architecture'] == 'aarch64' and ansible_facts.lsb.id | default(ansible_facts['distribution']) in ['Debian', 'Ubuntu'] and zabbix_repo_version != 7.2 %}-arm64{% endif %}"
zabbix_repo_deb_component: main
zabbix_repo_yum:
  - name: zabbix
    description: Zabbix Official Repository - $basearch
    baseurl: "{{ zabbix_repo_yum_schema }}://repo.zabbix.com/zabbix/{{ zabbix_repo_version | regex_search('^[0-9]+.[0-9]+') }}/{% if zabbix_repo_version == 7.2 %}stable/{% endif %}rhel/{{ ansible_distribution_major_version }}/$basearch/"
    gpgcheck: "{{ zabbix_repo_yum_gpgcheck }}"
    mode: "0644"
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
    state: present
  - name: zabbix-non-supported
    description: Zabbix Official Repository non-supported - $basearch
    baseurl: "{{ zabbix_repo_yum_schema }}://repo.zabbix.com/non-supported/rhel/{{ ansible_distribution_major_version }}/$basearch/"
    mode: "0644"
    gpgcheck: "{{ zabbix_repo_yum_gpgcheck }}"
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
    state: "{% if zabbix_repo_version == 7.2 %}absent{% else %}present{% endif %}"
zabbix_repo_apt_priority:
zabbix_repo_deb_gpg_key_url: http://repo.zabbix.com/zabbix-official-repo.key
zabbix_repo_deb_include_deb_src: true
zabbix_repo_rpm_gpg_key_url: http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-08EFA7DD

zabbix_repo_zypper_auto_import_keys: true
zabbix_repo_zypper_disable_gpg_check: false
zabbix_repo_zypper_schema: https
zabbix_repo_zypper:
  - name: zabbix
    description: Zabbix Official Repository
    repo: "{{ zabbix_repo_zypper_schema }}://repo.zabbix.com/zabbix/{{ zabbix_repo_version | regex_search('^[0-9]+.[0-9]+') }}/{% if zabbix_repo_version == 7.2 %}stable/{% endif %}sles/{{ ansible_distribution_major_version }}/$basearch/"
    disable_gpg_check: "{{ zabbix_repo_zypper_disable_gpg_check }}"
    auto_import_keys: "{{ zabbix_repo_zypper_auto_import_keys }}"
    state: present
